### ISSUE TITLE
Incorrect (twice?) shutdown when registered for shutdown

### ISSUE THREAD

**Issue by nnseva** [smira/txZMQ#58]
The factory which has been registered for shutdown ...

``` python
        self.zmqfactory = ZmqFactory()
        self.zmqfactory.registerForShutdown()
        self.receiver = MyZmqSubConnection(self,self.zmqfactory)
```

is shutted down later

``` python
       self.zmqfactory.shutdown()
```

As a result, the unhandled exception happens when the reactor is shutted down:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 307, in addCallback
    callbackKeywords=kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 296, in addCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/txzmq/factory.py", line 51, in shutdown
    for connection in self.connections.copy():
```

It probably useful either add an 'active' flag of the factory to avoid conflict when shutting down twice (manually and automatically), or unregister from the reactor to be shutted down automatically to avoid a conflict as such.

**Comment by smira** [comment]
@nnseva do you care to provide a patch?

**Comment by nnseva** [comment]
hmmm, I will try ...

**Comment by nnseva** [comment]
Here you are ...
```diff
--- txzmq/factory.py.orig       2015-03-13 13:27:05.735469274 +0300
+++ txzmq/factory.py    2015-03-13 13:36:12.191438709 +0300
@@ -27,6 +27,7 @@
     reactor = reactor
     ioThreads = 1
     lingerPeriod = 100
+    trigger = None

     def __init__(self):
         """
@@ -55,6 +56,11 @@

         self.context.term()
         self.context = None
+        if self.trigger:
+            try:
+                reactor.removeSystemEventTrigger(self.trigger)
+            except Exception,ex:
+                pass # just ignore while triggered by the reactor

     def registerForShutdown(self):
         """
@@ -64,4 +70,4 @@
         It is recommended that this method is called on any
         created factory.
         """
-        reactor.addSystemEventTrigger('during', 'shutdown', self.shutdown)
+        self.trigger = reactor.addSystemEventTrigger('during', 'shutdown', self.shutdown)

```

**Comment by smira** [comment]
Could you please make PR out of that and add unit tests?

**Comment by nnseva** [comment]
don't understand how to test the reactor shutting-down phase a while ...

**Comment by nnseva** [comment]
see #59
